/* ============================================================
   FREEDOM HOME v1  ·  host on GitHub Pages as freedom-home.v1.js
   ------------------------------------------------------------
   ONE page that always knows the student's next step. Replaces
   lesson-hopping as the router: the Gateway's state response drives a
   client-side nextStep() and this loader renders exactly one primary
   action at a time — wizard → Day-1 Freedom Power Hour (4 AI tools
   inline, done-button ticks) → daily rhythm (jumpstart → coach →
   rewiring tool → daily log) → progress.

   Lesson stub (generated by ai_tools/tools/home-snippet.js):
     <div id="freedom-home"
          data-engine="https://script.google.com/macros/s/…/exec"
          data-key="at_…"
          data-full-tracker-url="https://…lesson URL of the full tracker…"
          [data-draft="1"]></div>
     <script src="https://dfonvielle.github.io/ai-tools-widget/ai-tools-widget.js"><\/script>
     <script src="https://USER.github.io/freedom-tracker/freedom-home.v1.js"><\/script>
   (coach.v3.js is injected by THIS loader when the daily rail first
   renders, from the same folder this script was served from.)

   RIDES ON (no new Gateway actions):
     state / getDay / save / setupSave / recover / activate /
     progressReview  — same contracts as loader.v7.js.
   PAIRS WITH:
     ai-tools-widget (window.AgtWidget.mount/unmount +
       data-first-message-from + data-session-key), and coach.v3.js
       (fc:prompt / fc:prompt-send events; we set window.FREEDOM_HOME).
   IDENTITY: shares ag_ft_token + ag_ft_identity_v6 with loader.v7 and
   coach.v3, so activation done anywhere works everywhere. Only the
   state snapshot cache is home-specific (ag_fh_cache_v1).

   TEST HOOK: when window.__FH_MOCK_CALL is defined (test_home.html),
   every Gateway call routes there instead of the network, and identity
   is stubbed. Production pages never define it.
   ============================================================ */
(function () {
  'use strict';

  // Must be true BEFORE coach.v3 renders any prompt box (we also inject
  // that script ourselves, so the ordering is guaranteed).
  window.FREEDOM_HOME = true;

  var CONFIG = {
    GATEWAY_URL: 'https://script.google.com/macros/s/AKfycbxokJhAPaX6PvvQDJPQAJZa2NFQ1F5_bwz22yZQoqPclSPCO4GPhzESsB18AidstYmQ/exec',
    APP_KEY: '2br02b_AKfycbxokJhAPaX6PvvQDJPQAJZa2NFQ1F5_bwz22yZQoqPclSPCO4GPhzESsB18AidstYmQ_otter',
    CONTAINER_ID: 'freedom-home',
    IDENTITY_CACHE_HOURS: 24,
    STATE_CACHE_HOURS: 48
  };

  // Where THIS script was served from — coach.v3.js is injected from the
  // same folder. Captured at evaluation time (currentScript is null later).
  var SCRIPT_SRC = (document.currentScript && document.currentScript.src) || '';

  /* ============================================================
   * COPY — EDIT ALL STUDENT-FACING TEXT HERE. {NAME}/{DAY}/{ANCHOR}
   * are replaced at render time.
   * ============================================================ */
  var COPY = {
    LOADING: 'Loading your Freedom Page…',
    HEADER_DAY: 'Day {DAY}',
    HEADER_HI: 'Hi{NAME} — here’s your next step.',
    REFRESH_BTN: '↻ Refresh',
    FOOTER_FULL_TRACKER: 'Open your full Freedom Tracker →',
    NOT_CONFIGURED: 'This page is missing its tool settings (data-engine / data-key). The daily steps still work — but the AI tools can’t load. If you’re the site owner, re-paste the lesson snippet.',

    // Wizard (mirrors loader.v7 wording)
    WIZ1_TITLE: 'Welcome{NAME}! Let’s set up your project.',
    WIZ1_LABEL: 'I want to make it easier and more enjoyable to be free from the following Unwanted Behavior (UB):',
    WIZ1_PLACEHOLDER: 'Your behavior — or just write "my UB" to keep it private',
    WIZ1_BUTTON: 'Continue →',
    WIZ1_ERROR: 'Name the behavior — "my UB" is fine if you’d rather keep it private.',
    WIZ2_TITLE: 'Your baseline Freedom Scores before any rewiring',
    WIZ2_SUB: 'In 7 days, you’ll look back at these numbers to see proof of change. There are no bad scores (all zeros are fine)! Low initial scores only make the improvement more satisfying.',
    WIZ2_BUTTON: 'Save my baseline →',
    SCORE_ERROR: 'Scores must be whole numbers from 0 to 10.',
    WIZ3_TITLE: 'Pick your daily rewiring moment',
    WIZ3_SUB: 'Each morning you’ll do 30 seconds to 2 minutes of rewiring (the Happiness & Success Jumpstart). Anchor it to something you already do every morning — while brushing your teeth, while the coffee brews, in the shower.',
    WIZ3_LABEL: 'I’ll do my morning rewiring (the H&S Jumpstart) at this time and place:',
    WIZ3_PLACEHOLDER: 'e.g. 7am, while my coffee brews',
    WIZ3_BUTTON: 'Continue →',
    WIZ3_ERROR: 'Pick a real time and place — e.g. "7am, while my coffee brews".',
    WIZ4_TITLE: 'You’re set. Here’s your goal & plan:',
    WIZ4_UB_PREFIX: 'I want to make it easier and more enjoyable to be free from: ',
    WIZ4_JS_PREFIX: 'Every morning, 30 seconds–2 minutes of rewiring at: ',
    WIZ4_BUTTON: 'Let’s Get Started →',
    SAVING: 'Saving…',

    // Day 0
    D0_TITLE: 'Day 0 — Get ready',
    D0_CHECK: 'I understand how I’ll make it easier and more enjoyable to not do my UB, and I’m looking forward to the rewiring!',
    D0_PLAN_LABEL: 'My Day 1 Freedom Power Hour time and place:',
    D0_PLAN_PLACEHOLDER: 'e.g. tomorrow 8am, at my desk',
    D0_SAVE: 'Save',
    D0_START_NOW: 'Start my Freedom Power Hour now →',
    D0_NOTE: 'Your Power Hour is about an hour with four AI tools, one after another. You can do it now, or at the time you picked.',

    // Power Hour
    PH_STRIP_TITLE: 'Day 1 — Freedom Power Hour',
    PH_TOOL_OF: 'Tool {I} of 4: {NAME}',
    PH_INTRO: 'Work with this tool below. When it wraps up, tap the button and the next tool appears right here.',
    PH_DONE_BTN: 'I finished this tool → Continue',
    PH_DONE_SAVING: 'Saving…',
    PH_SCORES_TITLE: 'One last thing: your Freedom Scores after the Power Hour',
    PH_SCORES_SUB: 'Compare these to your baseline any time in your full tracker.',
    PH_SCORES_BTN: 'Save my scores →',
    PH_RESUME_NOTE: 'Stop anytime — this page remembers exactly where you left off.',
    PH_CELEBRATE_TITLE: '🎉 Day 1 complete — massive rewiring head start!',
    PH_CELEBRATE_TEXT: 'You just did the single biggest day of this whole process. From tomorrow, each day takes just 7–22 minutes. Come back to this same page — it will show you exactly what to do.',
    PH_REVIEW_LINK: 'Revisit a Power Hour tool',
    WITHDRAWAL_LINK: 'Worried about withdrawal or cravings? Try the optional Withdrawal Helper →',
    WITHDRAWAL_TITLE: 'Optional: Withdrawal Helper',
    WITHDRAWAL_SUB: 'A focused tool for handling withdrawal worries. Totally optional — use it if it speaks to you.',
    WITHDRAWAL_DONE: 'Done with this tool → back',
    COACH_LOGGED: 'Your coach logged this for you ✓',
    SETUP_POLLING: 'Checking automatically — this usually takes under a minute…',
    PROJ_NEW: '+ Start a new project',

    // Daily rail
    DAILY_STRIP_TITLE: 'Today’s rhythm — three small steps',
    STEP1_TITLE: '1 · Morning rewiring (30 sec–2 min)',
    STEP1_CHECK: 'I did my Happiness & Success Jumpstart',
    STEP1_ANCHOR: 'Your moment: {ANCHOR}',
    STEP2_TITLE: '2 · Talk it out, then rewire',
    STEP2_SUB: 'Tell your coach what’s going on (or tap “Recommend my next move”). When your coach hands you a loaded prompt, one tap sends it into your rewiring tool below.',
    STEP2_TOOL_WAITING: 'Your rewiring tool will open here — talk to your coach first, or start it directly:',
    STEP2_TOOL_DIRECT: 'Start my rewiring session without the coach →',
    STEP2_TOOL_LOADED: 'Your tool is loaded with what you and your coach worked out — continue below.',
    STEP3_TITLE: '3 · Log your day (1 minute)',
    STEP3_MINUTES: 'Minutes with the rewiring tool today (0 if none):',
    STEP3_SAVE: 'Save my day →',
    STEP3_SAVED: 'Saved ✓ — see you tomorrow!',
    CONF_FOREVER: 'I’m 100% confident I can rewire my brain — never ask me about confidence again.',

    // Progress
    PROGRESS_BTN: 'See my progress',
    PROGRESS_TITLE: 'Your movement so far',
    PROGRESS_BASELINE: 'Baseline',
    PROGRESS_EMPTY: 'Log a day’s scores and your movement shows up here.',

    // Activation (mirrors loader.v7)
    ACTIVATE_TITLE: 'Activate your Freedom Page',
    ACTIVATE_SIGNED_IN: 'You’re signed in as ',
    ACTIVATE_SUB: 'Enter the activation code from your welcome email.',
    ACTIVATE_NO_EMAIL: 'Enter the email you bought with.',
    ACTIVATE_BUTTON: 'Activate →',
    ACTIVATE_NEED_CODE: 'Enter your activation code.',
    SETUP_TITLE: 'Setting up your tracker…',
    SETUP_TEXT: 'If you just purchased, your tracker is being created — give it a moment, then tap Retry. You’ll also get an activation link by email.',
    SETUP_RETRY: 'Retry',
    SETUP_MANUAL: 'Have an activation code? Enter it instead.',
    STALE_TOKEN: 'Please activate again — your saved access looked stale.'
  };

  // The Power Hour sequence (order is the method — do not reorder) and
  // the daily tool routing. fieldKey = the Gateway save key for the tick.
  var TOOLS = {
    powerHour: [
      { bot: 'bh_nbwe',    fieldKey: 'd1_t1', name: 'No-Brainer Willpower Eliminator' },
      { bot: 'bh_minplan', fieldKey: 'd1_t2', name: 'Minimalist Plan' },
      { bot: 'bh_feelgs',  fieldKey: 'd1_t3', name: 'Feel Good Start' },
      { bot: 'bh_cjc',     fieldKey: 'd1_t4', name: 'Create Joyous Chaos' }
    ],
    dailyDefault: 'bh_rbf',
    // coach.v3's fc:prompt-send detail.tool contains 'Fear' when the
    // guided flow routed to the Fear & Anxiety tool (CoachFlow strings).
    routeBot: function (toolName) {
      return (/fear/i.test(String(toolName || ''))) ? 'bh_fearanxiety' : 'bh_rbf';
    }
  };

  // token + identity SHARED with loader.v7/coach.v3 (activate once, works
  // everywhere). Only the state snapshot cache is home-specific.
  var LS = { identity: 'ag_ft_identity_v6', token: 'ag_ft_token', cache: 'ag_fh_cache_v1' };

  var state = {
    identity: null, token: null,
    engine: '', engineKey: '', draft: false, fullTrackerUrl: '',
    projects: [], activeProjectId: null,
    currentDay: 0, maxTrackedDay: 7,
    writable: true,
    confidence: { optedOut: false, since: '' },
    setup: { stage: 0, ub: '', jumpstart: '' },
    scoreQuestions: null,
    completion: null,
    day: null,          // current-day data from the Gateway (readDay_ shape)
    phDay: null,        // day-1 data while running the Power Hour from Day 0
    phIndex: null,      // explicit Power Hour position (null = derive)
    forcedPhase: null,  // student navigation override ('power_hour' from Day 0 / review)
    coachLoaded: false, // coach.v3 script injected?
    toolMountedBot: '', // bot currently mounted in #fh-tool
    dirty: false,
    _recoverTried: false
  };
  var rootEl = null;
  var setupPollTimer = null;   // "Setting up…" auto-retry (renderSettingUp)
  function clearSetupPoll_() {
    if (setupPollTimer) { window.clearInterval(setupPollTimer); setupPollTimer = null; }
  }

  /* ============================================================
   * Small helpers (same shapes as loader.v7)
   * ============================================================ */
  function readLS(k) { try { return localStorage.getItem(k); } catch (e) { return null; } }
  function writeLS(k, v) { try { localStorage.setItem(k, v); } catch (e) {} }
  function esc(s) {
    return String(s == null ? '' : s)
      .replace(/&/g, '&amp;').replace(/</g, '&lt;')
      .replace(/>/g, '&gt;').replace(/"/g, '&quot;');
  }
  function setMsg(id, text, ok) {
    var el = document.getElementById(id);
    if (!el) return;
    el.textContent = text;
    el.className = 'fh-msg ' + (ok ? 'fh-good' : 'fh-bad');
  }
  function validText(s) { return !!String(s || '').trim(); }
  function validScore(v) {
    if (v === '' || v == null) return false;
    var n = Number(v);
    return !isNaN(n) && n >= 0 && n <= 10 && n === Math.floor(n);
  }
  function fieldVal(dayData, key) {
    if (!dayData || !dayData.fields) return null;
    for (var i = 0; i < dayData.fields.length; i++) {
      if (dayData.fields[i].key === key) return dayData.fields[i].value;
    }
    return null;
  }
  function asJson(r) {
    if (!r.ok) throw new Error('HTTP ' + r.status);
    return r.json();
  }

  /* ============================================================
   * URL params + identity (lifted from loader.v7; same behavior)
   * ============================================================ */
  function candidateUrls() {
    var urls = [];
    try { urls.push(window.location.href); } catch (e) {}
    try { if (window.parent && window.parent !== window) urls.push(window.parent.location.href); } catch (e) {}
    try { if (document.referrer) urls.push(document.referrer); } catch (e) {}
    return urls;
  }
  function readParam(name) {
    var urls = candidateUrls();
    for (var i = 0; i < urls.length; i++) {
      try {
        var v = new URL(urls[i]).searchParams.get(name);
        if (v) return v.trim();
      } catch (e) {}
    }
    return null;
  }
  function captureMagicLinkToken() {
    var t = readParam('ag_token');
    if (t) {
      var prev = readLS(LS.token);
      writeLS(LS.token, t);
      if (prev && prev !== t) clearStateCache();
    }
  }
  function stripTokenFromUrl() {
    try {
      var url = new URL(window.location.href);
      if (url.searchParams.has('ag_token')) {
        url.searchParams.delete('ag_token');
        window.history.replaceState({}, document.title, url.toString());
      }
    } catch (e) {}
  }
  function handleResetParam() { if (readParam('ag_reset')) resetStorage(); }
  function resetStorage() {
    try { localStorage.removeItem(LS.token); } catch (e) {}
    try { localStorage.removeItem(LS.identity); } catch (e) {}
    clearStateCache();
  }
  function resetTokenOnly() {
    state.token = null;
    try { localStorage.removeItem(LS.token); } catch (e) {}
  }

  function getIdentity() {
    return fetchSystemeIdentity()
      .then(function (id) {
        writeLS(LS.identity, JSON.stringify({ v: id, at: Date.now() }));
        return id;
      })
      .catch(function () {
        return readIdentityCache() || { accountId: '', email: '', firstName: '' };
      });
  }
  function fetchSystemeIdentity() {
    return Promise.all([
      fetch('/api/user/user-data', { credentials: 'same-origin' }).then(asJson),
      fetch('/api/settings/profile', { credentials: 'same-origin' }).then(asJson)
    ]).then(function (results) {
      var userData = results[0] || {};
      var profile = (results[1] && results[1].user) || {};
      var id = {
        accountId: String(userData.id || ''),
        email: String(profile.email || '').toLowerCase(),
        firstName: String(profile.firstName || userData.firstName || '')
      };
      if (!id.accountId && !id.email) throw new Error('No identity in response');
      return id;
    });
  }
  function readIdentityCache() {
    try {
      var raw = readLS(LS.identity);
      if (!raw) return null;
      var parsed = JSON.parse(raw);
      if ((Date.now() - parsed.at) / 3600000 > CONFIG.IDENTITY_CACHE_HOURS) return null;
      return parsed.v;
    } catch (e) { return null; }
  }
  function identityMatches_(a, b) {
    a = a || {}; b = b || {};
    var aid = String(a.accountId || ''), bid = String(b.accountId || '');
    if (aid && bid) { return aid === bid; }
    var ae = String(a.email || '').toLowerCase(), be = String(b.email || '').toLowerCase();
    if (ae && be) { return ae === be; }
    return true;
  }

  /* ============================================================
   * State snapshot cache (cache-then-refresh, home-specific key)
   * ============================================================ */
  function readStateCache() {
    try {
      var raw = localStorage.getItem(LS.cache);
      if (!raw) return null;
      var parsed = JSON.parse(raw);
      if (parsed.token !== state.token) return null;
      if ((Date.now() - parsed.at) / 3600000 > CONFIG.STATE_CACHE_HOURS) return null;
      return parsed;
    } catch (e) { return null; }
  }
  function writeStateCache() {
    try {
      localStorage.setItem(LS.cache, JSON.stringify({
        at: Date.now(), token: state.token,
        snapshot: {
          projects: state.projects, activeProjectId: state.activeProjectId,
          currentDay: state.currentDay, maxTrackedDay: state.maxTrackedDay,
          writable: state.writable, confidence: state.confidence,
          canCreateProject: state.canCreateProject === true,
          setup: state.setup, scoreQuestions: state.scoreQuestions,
          completion: state.completion, day: state.day,
          firstName: (state.identity && state.identity.firstName) || ''
        }
      }));
    } catch (e) {}
  }
  function clearStateCache() { try { localStorage.removeItem(LS.cache); } catch (e) {} }
  function hydrateFromCache(snap) {
    state.projects = snap.projects || [];
    state.activeProjectId = snap.activeProjectId;
    state.currentDay = snap.currentDay || 0;
    state.maxTrackedDay = snap.maxTrackedDay || 7;
    state.writable = (snap.writable === false) ? false : true;
    state.confidence = snap.confidence || { optedOut: false, since: '' };
    state.canCreateProject = snap.canCreateProject === true;
    state.setup = snap.setup || state.setup;
    state.scoreQuestions = snap.scoreQuestions || null;
    state.completion = snap.completion || null;
    state.day = snap.day || null;
  }

  /* ============================================================
   * Gateway client (mock-aware — see header TEST HOOK)
   * ============================================================ */
  function callGateway(payload) {
    payload.appKey = CONFIG.APP_KEY;
    payload.accountId = (state.identity && state.identity.accountId) || '';
    payload.email = (state.identity && state.identity.email) || '';
    payload.token = state.token || '';
    if (typeof window.__FH_MOCK_CALL === 'function') {
      return Promise.resolve(window.__FH_MOCK_CALL(payload));
    }
    return fetch(CONFIG.GATEWAY_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'text/plain;charset=utf-8' },
      body: JSON.stringify(payload)
    }).then(asJson);
  }

  function adoptState(data) {
    state.projects = data.projects || [];
    state.activeProjectId = data.activeProjectId;
    state.currentDay = data.currentDay || 0;
    state.maxTrackedDay = data.maxTrackedDay || 7;
    state.writable = (data.writable === false) ? false : true;
    state.confidence = data.confidence || { optedOut: false, since: '' };
    state.canCreateProject = data.canCreateProject === true;
    state.setup = data.setup || { stage: 0, ub: '', jumpstart: '' };
    state.scoreQuestions = data.scoreQuestions || null;
    if (data.completion) state.completion = data.completion;
    if (data.day) state.day = data.day;
    if (data.firstName && state.identity && !state.identity.firstName) {
      state.identity.firstName = data.firstName;
    }
  }

  function loadState(background) {
    callGateway({ action: 'state', projectId: state.activeProjectId })
      .then(function (data) {
        if (!data.ok) {
          if (background) return;
          resetTokenOnly();
          clearStateCache();
          if (state._recoverTried) { return renderPairing(COPY.STALE_TOKEN); }
          return attemptRecover(COPY.STALE_TOKEN);
        }
        state._recoverTried = false;
        adoptState(data);
        writeStateCache();
        if (!background || safeToRerender()) route();
      })
      .catch(function () {
        if (!background) renderFatal('Could not load your Freedom Page. Check your connection and try again.');
      });
  }
  function safeToRerender() {
    if (state.dirty) return false;
    try {
      var a = document.activeElement;
      if (a && rootEl.contains(a) && (a.tagName === 'INPUT' || a.tagName === 'TEXTAREA' || a.tagName === 'SELECT')) return false;
    } catch (e) {}
    return true;
  }

  /* ============================================================
   * Touchless recover + activation (lifted from loader.v7)
   * ============================================================ */
  function attemptRecover(notice) {
    state._recoverTried = true;
    var haveIdentity = state.identity && (state.identity.accountId || state.identity.email);
    if (!haveIdentity) { return renderPairing(notice || ''); }
    rootEl.innerHTML = shellLoading();
    callGateway({ action: 'recover' }).then(function (data) {
      if (data.ok && data.token) {
        persistTokenFromResponse(data);
        clearStateCache();
        rootEl.innerHTML = shellLoading();
        loadState(false);
        return;
      }
      if (data.ok && data.notFound) { return renderSettingUp(); }
      return renderPairing(notice || data.error || '');
    }).catch(function () {
      renderPairing(notice || '');
    });
  }
  function persistTokenFromResponse(data) {
    if (data && data.token && data.token !== state.token) {
      state.token = data.token;
      writeLS(LS.token, data.token);
    }
  }
  function verifyIdentityThenRefresh_(paintedId) {
    fetchSystemeIdentity().then(function (fresh) {
      writeLS(LS.identity, JSON.stringify({ v: fresh, at: Date.now() }));
      if (!identityMatches_(paintedId, fresh)) {
        resetTokenOnly();
        clearStateCache();
        state.identity = fresh;
        return attemptRecover('');
      }
      state.identity = fresh;
      loadState(true);
    }).catch(function () {
      loadState(true);
    });
  }

  function renderSettingUp() {
    rootEl.innerHTML =
      '<div class="fh-card">' +
        '<h3>' + esc(COPY.SETUP_TITLE) + '</h3>' +
        '<p class="fh-sub">' + esc(COPY.SETUP_TEXT) + '</p>' +
        '<p class="fh-sub">' + esc(COPY.SETUP_POLLING) + '</p>' +
        '<button class="fh-btn" id="fh-setup-retry">' + esc(COPY.SETUP_RETRY) + '</button>' +
        '<div class="fh-linkline"><a href="#" id="fh-setup-manual">' + esc(COPY.SETUP_MANUAL) + '</a></div>' +
      '</div>';
    document.getElementById('fh-setup-retry').addEventListener('click', function () {
      clearSetupPoll_();
      state._recoverTried = false;
      attemptRecover('');
    });
    document.getElementById('fh-setup-manual').addEventListener('click', function (e) {
      e.preventDefault();
      clearSetupPoll_();
      renderPairing('');
    });
    // Auto-retry: a buyer who clicks through within seconds of purchase can
    // beat the enrollment webhook. Poll quietly — 4 tries × 15s stays well
    // under the Gateway's recover rate cap (8 per 5 min) and leaves budget
    // for manual retries.
    clearSetupPoll_();
    var polls = 0;
    setupPollTimer = window.setInterval(function () {
      polls++;
      if (polls > 4) { clearSetupPoll_(); return; }
      callGateway({ action: 'recover' }).then(function (data) {
        if (data.ok && data.token) {
          clearSetupPoll_();
          persistTokenFromResponse(data);
          clearStateCache();
          rootEl.innerHTML = shellLoading();
          loadState(false);
        }
      }).catch(function () {});
    }, 15000);
  }
  function renderPairing(notice) {
    var emailNote = state.identity && state.identity.email
      ? COPY.ACTIVATE_SIGNED_IN + '<strong>' + esc(state.identity.email) + '</strong>.'
      : esc(COPY.ACTIVATE_NO_EMAIL);
    rootEl.innerHTML =
      '<div class="fh-card">' +
        '<h3>' + esc(COPY.ACTIVATE_TITLE) + '</h3>' +
        (notice ? '<div class="fh-note">' + esc(notice) + '</div>' : '') +
        '<p class="fh-sub">' + emailNote + ' ' + esc(COPY.ACTIVATE_SUB) + '</p>' +
        (state.identity && state.identity.email ? '' : '<input type="email" id="fh-email" placeholder="Your email" />') +
        '<input type="text" id="fh-token" placeholder="Activation code (from your welcome email)" />' +
        '<button class="fh-btn" id="fh-activate">' + esc(COPY.ACTIVATE_BUTTON) + '</button>' +
        '<div class="fh-msg" id="fh-pair-msg"></div>' +
      '</div>';
    document.getElementById('fh-activate').addEventListener('click', function () {
      var manualEmail = document.getElementById('fh-email');
      if (manualEmail && manualEmail.value) {
        state.identity = state.identity || {};
        state.identity.email = manualEmail.value.trim().toLowerCase();
      }
      var t = document.getElementById('fh-token').value.trim().toLowerCase();
      if (!t) return setMsg('fh-pair-msg', COPY.ACTIVATE_NEED_CODE, false);
      state.token = t;
      setMsg('fh-pair-msg', 'Checking…', true);
      callGateway({ action: 'activate' }).then(function (data) {
        if (!data.ok) return setMsg('fh-pair-msg', data.error, false);
        persistTokenFromResponse(data);
        writeLS(LS.token, state.token);
        clearStateCache();
        state._recoverTried = false;
        rootEl.innerHTML = shellLoading();
        loadState(false);
      }).catch(function (err) { setMsg('fh-pair-msg', String(err), false); });
    });
  }
  function renderFatal(message) {
    rootEl.innerHTML = '<div class="fh-card"><div class="fh-msg fh-bad">' + esc(message) + '</div>' +
      '<button class="fh-btn" id="fh-retry">Try again</button></div>';
    document.getElementById('fh-retry').addEventListener('click', function () {
      state.token = readLS(LS.token);
      boot();
    });
  }

  /* ============================================================
   * nextStep — THE router. Pure function of state (+ student nav).
   * ============================================================ */
  function nextStep() {
    if (state.forcedPhase) return { phase: state.forcedPhase };
    if (!state.setup || state.setup.stage < 4) return { phase: 'wizard' };
    if (state.currentDay <= 1) {
      var phDay = (state.currentDay === 1) ? state.day : state.phDay;
      if (state.currentDay === 0 && !phDay) return { phase: 'day0' };
      var idx = firstUntickedTool(phDay);
      if (idx >= 0) return { phase: 'power_hour', index: idx };
      if (!(state.completion && state.completion[1])) return { phase: 'after_scores' };
      return { phase: 'day1_done' };
    }
    return { phase: 'daily' };
  }
  function firstUntickedTool(phDay) {
    if (!phDay) return 0;
    for (var i = 0; i < TOOLS.powerHour.length; i++) {
      if (!fieldVal(phDay, TOOLS.powerHour[i].fieldKey)) return i;
    }
    return -1;
  }

  /* ============================================================
   * Shell + routing
   * ============================================================ */
  function shellLoading() { return '<div class="fh-card fh-center">' + esc(COPY.LOADING) + '</div>'; }

  function renderShell(bodyHtml) {
    var name = (state.identity && state.identity.firstName) ? ' ' + state.identity.firstName : '';
    var dayLabel = COPY.HEADER_DAY.replace('{DAY}', String(state.currentDay));

    // Project picker — hidden for the normal one-project student; appears
    // only with multiple projects or the unlimited entitlement (the Gateway
    // decides entitlement; we only render what it says — never decide here).
    var pickerHtml = '';
    if ((state.projects && state.projects.length > 1) || state.canCreateProject) {
      var opts = '';
      for (var pi = 0; pi < (state.projects || []).length; pi++) {
        var p = state.projects[pi];
        var pid = String(p.projectId);
        opts += '<option value="' + esc(pid) + '"' + (pid === String(state.activeProjectId) ? ' selected' : '') + '>'
          + esc(p.label || ('Project ' + pid)) + '</option>';
      }
      if (state.canCreateProject) { opts += '<option value="__new">' + esc(COPY.PROJ_NEW) + '</option>'; }
      pickerHtml = '<select id="fh-proj" class="fh-proj">' + opts + '</select>';
    }

    rootEl.innerHTML =
      '<div class="fh-wrap">' +
        '<div class="fh-header">' +
          '<div><div class="fh-daychip">' + esc(dayLabel) + '</div>' +
          '<div class="fh-hi">' + esc(COPY.HEADER_HI.replace('{NAME}', name ? ',' + name : '')) + '</div></div>' +
          '<div class="fh-hdr-right">' + pickerHtml +
            '<button class="fh-refresh" id="fh-refresh">' + esc(COPY.REFRESH_BTN) + '</button>' +
          '</div>' +
        '</div>' +
        '<div id="fh-body">' + bodyHtml + '</div>' +
        (state.fullTrackerUrl
          ? '<div class="fh-footer"><a href="' + esc(state.fullTrackerUrl) + '">' + esc(COPY.FOOTER_FULL_TRACKER) + '</a></div>'
          : '') +
      '</div>';
    var rb = document.getElementById('fh-refresh');
    if (rb) rb.addEventListener('click', function () {
      rb.textContent = '…';
      state.forcedPhase = null;
      callGateway({ action: 'state', projectId: state.activeProjectId, fresh: true }).then(function (data) {
        if (data.ok) { adoptState(data); writeStateCache(); }
        route();
      }).catch(function () { route(); });
    });
    var ps = document.getElementById('fh-proj');
    if (ps) ps.addEventListener('change', function () {
      var v = this.value;
      clearSetupPoll_();
      state.forcedPhase = null; state.day = null; state.phDay = null; state.phIndex = null;
      rootEl.innerHTML = shellLoading();
      if (v === '__new') {
        // Same flow as loader.v7's "+ Start a new project": create in place,
        // then reload state — the fresh project lands in the setup wizard.
        callGateway({ action: 'createProject' }).then(function (data) {
          state.activeProjectId = (data && data.ok && data.projectId != null) ? String(data.projectId) : null;
          clearStateCache();
          loadState(false);
        }).catch(function () { loadState(false); });
        return;
      }
      state.activeProjectId = v;
      loadState(false);
    });
  }

  function route() {
    clearSetupPoll_();
    unmountTool();
    var step = nextStep();
    if (step.phase === 'wizard') return renderWizard();
    if (step.phase === 'day0') return renderDay0();
    if (step.phase === 'power_hour') return renderPowerHour(step.index != null ? step.index : 0);
    if (step.phase === 'after_scores') return renderAfterScores();
    if (step.phase === 'day1_done') return renderDay1Done();
    return renderDaily();
  }

  /* ============================================================
   * WIZARD (same 4 setupSave steps as loader.v7)
   * ============================================================ */
  function renderWizard() {
    var stage = state.setup.stage;
    if (stage === 0) return wizardStepUb();
    if (stage === 1) return wizardStepBaseline();
    if (stage === 2) return wizardStepJumpstart();
    return wizardStepGoalPlan();
  }
  function wizardDots(step) {
    var html = '<div class="fh-dots">';
    for (var i = 1; i <= 4; i++) html += '<span class="fh-dot' + (i <= step ? ' fh-dot-on' : '') + '"></span>';
    return html + '<span class="fh-dots-label">Step ' + step + ' of 4</span></div>';
  }
  function wizardStepUb() {
    var name = (state.identity && state.identity.firstName) ? ', ' + state.identity.firstName : '';
    renderShell(
      '<div class="fh-card">' + wizardDots(1) +
        '<h3>' + esc(COPY.WIZ1_TITLE.replace('{NAME}', name)) + '</h3>' +
        '<label class="fh-label">' + esc(COPY.WIZ1_LABEL) + '</label>' +
        '<textarea id="fh-ub" rows="3" placeholder="' + esc(COPY.WIZ1_PLACEHOLDER) + '">' + esc(state.setup.ub) + '</textarea>' +
        '<button class="fh-btn" id="fh-next">' + esc(COPY.WIZ1_BUTTON) + '</button>' +
        '<div class="fh-msg" id="fh-wiz-msg"></div>' +
      '</div>');
    document.getElementById('fh-next').addEventListener('click', function () {
      var ub = document.getElementById('fh-ub').value.trim();
      if (!validText(ub)) return setMsg('fh-wiz-msg', COPY.WIZ1_ERROR, false);
      setMsg('fh-wiz-msg', COPY.SAVING, true);
      callGateway({ action: 'setupSave', projectId: state.activeProjectId, step: 'ub', ub: ub })
        .then(function (data) {
          if (!data.ok) return setMsg('fh-wiz-msg', data.error, false);
          state.setup.stage = data.stage;
          state.setup.ub = data.ub;
          writeStateCache();
          renderWizard();
        })
        .catch(function (err) { setMsg('fh-wiz-msg', String(err), false); });
    });
  }
  function scoreQuestion(key) {
    var q = state.scoreQuestions || {};
    var fallback = { easy: 'Easy (0-10)', enjoy: 'Enjoyable (0-10)', conf: 'Confidence (0-10)' };
    return q[key] || fallback[key];
  }
  function scoreInputHtml(key, idPrefix, value) {
    return '<div class="fh-field"><label class="fh-label">' + esc(scoreQuestion(key)) + '</label>' +
      '<input type="number" min="0" max="10" step="1" id="' + idPrefix + key + '" placeholder="0-10" value="' + esc(value == null ? '' : value) + '" /></div>';
  }
  function wizardStepBaseline() {
    renderShell(
      '<div class="fh-card">' + wizardDots(2) +
        '<h3>' + esc(COPY.WIZ2_TITLE) + '</h3>' +
        '<p class="fh-sub">' + esc(COPY.WIZ2_SUB) + '</p>' +
        scoreInputHtml('easy', 'fh-sc-', null) +
        scoreInputHtml('enjoy', 'fh-sc-', null) +
        scoreInputHtml('conf', 'fh-sc-', null) +
        '<button class="fh-btn" id="fh-next">' + esc(COPY.WIZ2_BUTTON) + '</button>' +
        '<div class="fh-msg" id="fh-wiz-msg"></div>' +
      '</div>');
    document.getElementById('fh-next').addEventListener('click', function () {
      var scores = {};
      var keys = ['easy', 'enjoy', 'conf'];
      for (var i = 0; i < keys.length; i++) {
        var v = document.getElementById('fh-sc-' + keys[i]).value;
        if (!validScore(v)) return setMsg('fh-wiz-msg', COPY.SCORE_ERROR, false);
        scores[keys[i]] = Number(v);
      }
      setMsg('fh-wiz-msg', COPY.SAVING, true);
      callGateway({ action: 'setupSave', projectId: state.activeProjectId, step: 'baseline', scores: scores })
        .then(function (data) {
          if (!data.ok) return setMsg('fh-wiz-msg', data.error, false);
          state.setup.stage = data.stage;
          writeStateCache();
          renderWizard();
        })
        .catch(function (err) { setMsg('fh-wiz-msg', String(err), false); });
    });
  }
  function wizardStepJumpstart() {
    renderShell(
      '<div class="fh-card">' + wizardDots(3) +
        '<h3>' + esc(COPY.WIZ3_TITLE) + '</h3>' +
        '<p class="fh-sub">' + esc(COPY.WIZ3_SUB) + '</p>' +
        '<label class="fh-label">' + esc(COPY.WIZ3_LABEL) + '</label>' +
        '<input type="text" id="fh-js" placeholder="' + esc(COPY.WIZ3_PLACEHOLDER) + '" value="' + esc(state.setup.jumpstart) + '" />' +
        '<button class="fh-btn" id="fh-next">' + esc(COPY.WIZ3_BUTTON) + '</button>' +
        '<div class="fh-msg" id="fh-wiz-msg"></div>' +
      '</div>');
    document.getElementById('fh-next').addEventListener('click', function () {
      var js = document.getElementById('fh-js').value.trim();
      if (!validText(js)) return setMsg('fh-wiz-msg', COPY.WIZ3_ERROR, false);
      setMsg('fh-wiz-msg', COPY.SAVING, true);
      callGateway({ action: 'setupSave', projectId: state.activeProjectId, step: 'jumpstart', jumpstart: js })
        .then(function (data) {
          if (!data.ok) return setMsg('fh-wiz-msg', data.error, false);
          state.setup.stage = data.stage;
          state.setup.jumpstart = data.jumpstart;
          writeStateCache();
          renderWizard();
        })
        .catch(function (err) { setMsg('fh-wiz-msg', String(err), false); });
    });
  }
  function wizardStepGoalPlan() {
    renderShell(
      '<div class="fh-card">' + wizardDots(4) +
        '<h3>' + esc(COPY.WIZ4_TITLE) + '</h3>' +
        '<p class="fh-goal">' + esc(COPY.WIZ4_UB_PREFIX) + '<strong>' + esc(state.setup.ub) + '</strong></p>' +
        '<p class="fh-goal">' + esc(COPY.WIZ4_JS_PREFIX) + '<strong>' + esc(state.setup.jumpstart) + '</strong></p>' +
        '<button class="fh-btn" id="fh-unlock">' + esc(COPY.WIZ4_BUTTON) + '</button>' +
        '<div class="fh-msg" id="fh-wiz-msg"></div>' +
      '</div>');
    document.getElementById('fh-unlock').addEventListener('click', function () {
      setMsg('fh-wiz-msg', 'Unlocking…', true);
      callGateway({ action: 'setupSave', projectId: state.activeProjectId, step: 'complete' })
        .then(function (data) {
          if (!data.ok) return setMsg('fh-wiz-msg', data.error, false);
          state.setup.stage = 4;
          state.currentDay = data.currentDay;
          state.day = data.day || null;
          state.completion = data.completion || null;
          writeStateCache();
          route();
        })
        .catch(function (err) { setMsg('fh-wiz-msg', String(err), false); });
    });
  }

  /* ============================================================
   * DAY 0 — get ready card + "start now" door into the Power Hour
   * ============================================================ */
  function renderDay0() {
    var d0 = (state.currentDay === 0) ? state.day : null;
    var checked = d0 ? !!fieldVal(d0, 'd0_all') : false;
    var plan = d0 ? (fieldVal(d0, 'd0_ph_plan') || '') : '';
    renderShell(
      '<div class="fh-card">' +
        '<h3>' + esc(COPY.D0_TITLE) + '</h3>' +
        '<label class="fh-check"><input type="checkbox" id="fh-d0-all"' + (checked ? ' checked' : '') + '/> ' + esc(COPY.D0_CHECK) + '</label>' +
        '<label class="fh-label">' + esc(COPY.D0_PLAN_LABEL) + '</label>' +
        '<input type="text" id="fh-d0-plan" placeholder="' + esc(COPY.D0_PLAN_PLACEHOLDER) + '" value="' + esc(plan) + '" />' +
        '<button class="fh-btn fh-secondary" id="fh-d0-save">' + esc(COPY.D0_SAVE) + '</button>' +
        '<div class="fh-msg" id="fh-d0-msg"></div>' +
        '<div class="fh-divider"></div>' +
        '<p class="fh-sub">' + esc(COPY.D0_NOTE) + '</p>' +
        '<button class="fh-btn" id="fh-d0-start">' + esc(COPY.D0_START_NOW) + '</button>' +
      '</div>');
    document.getElementById('fh-d0-save').addEventListener('click', function () {
      setMsg('fh-d0-msg', COPY.SAVING, true);
      callGateway({
        action: 'save', projectId: state.activeProjectId, day: 0,
        fields: {
          d0_all: document.getElementById('fh-d0-all').checked,
          d0_ph_plan: document.getElementById('fh-d0-plan').value.trim()
        }
      }).then(function (data) {
        if (!data.ok) return setMsg('fh-d0-msg', data.error, false);
        if (data.day) state.day = data.day;
        if (data.completion) state.completion = data.completion;
        writeStateCache();
        setMsg('fh-d0-msg', 'Saved ✓', true);
      }).catch(function (err) { setMsg('fh-d0-msg', String(err), false); });
    });
    document.getElementById('fh-d0-start').addEventListener('click', function () {
      callGateway({ action: 'getDay', projectId: state.activeProjectId, day: 1 })
        .then(function (data) {
          if (data.ok && data.day) { state.phDay = data.day; }
          state.forcedPhase = null;
          renderPowerHour(firstUntickedTool(state.phDay));
        })
        .catch(function () { renderPowerHour(0); });
    });
  }

  /* ============================================================
   * POWER HOUR — the 4 tools inline, in order, with done-ticks
   * ============================================================ */
  function phStripHtml(activeIdx) {
    var phDay = (state.currentDay === 1) ? state.day : state.phDay;
    var html = '<div class="fh-strip"><div class="fh-strip-title">' + esc(COPY.PH_STRIP_TITLE) + '</div><div class="fh-strip-steps">';
    for (var i = 0; i < TOOLS.powerHour.length; i++) {
      var done = !!fieldVal(phDay, TOOLS.powerHour[i].fieldKey);
      var cls = done ? 'fh-pip fh-pip-done' : (i === activeIdx ? 'fh-pip fh-pip-now' : 'fh-pip');
      html += '<span class="' + cls + '">' + (done ? '✓' : (i + 1)) + '</span>';
    }
    var scoresDone = !!(state.completion && state.completion[1]);
    html += '<span class="' + (scoresDone ? 'fh-pip fh-pip-done' : 'fh-pip') + '">' + (scoresDone ? '✓' : '★') + '</span>';
    return html + '</div></div>';
  }

  function renderPowerHour(idx) {
    if (idx < 0 || idx >= TOOLS.powerHour.length) return renderAfterScores();
    var tool = TOOLS.powerHour[idx];
    renderShell(
      phStripHtml(idx) +
      '<div class="fh-card">' +
        '<h3>' + esc(COPY.PH_TOOL_OF.replace('{I}', String(idx + 1)).replace('{NAME}', tool.name)) + '</h3>' +
        '<p class="fh-sub">' + esc(COPY.PH_INTRO) + ' ' + esc(COPY.PH_RESUME_NOTE) + '</p>' +
        '<div id="fh-tool"></div>' +
        '<button class="fh-btn" id="fh-ph-done">' + esc(COPY.PH_DONE_BTN) + '</button>' +
        '<div class="fh-msg" id="fh-ph-msg"></div>' +
      '</div>');
    mountTool(tool.bot, { sessionKey: 'ph-' + tool.bot });
    document.getElementById('fh-ph-done').addEventListener('click', function () {
      var btn = document.getElementById('fh-ph-done');
      btn.disabled = true;
      btn.textContent = COPY.PH_DONE_SAVING;
      var fields = {};
      fields[tool.fieldKey] = true;
      callGateway({ action: 'save', projectId: state.activeProjectId, day: 1, fields: fields })
        .then(function (data) {
          if (!data.ok) {
            btn.disabled = false; btn.textContent = COPY.PH_DONE_BTN;
            return setMsg('fh-ph-msg', data.error, false);
          }
          if (state.currentDay === 1) { state.day = data.day || state.day; }
          else { state.phDay = data.day || state.phDay; }
          if (data.completion) state.completion = data.completion;
          writeStateCache();
          route();
        })
        .catch(function (err) {
          btn.disabled = false; btn.textContent = COPY.PH_DONE_BTN;
          setMsg('fh-ph-msg', String(err), false);
        });
    });
  }

  function renderAfterScores() {
    var hideConf = !!(state.confidence && state.confidence.optedOut);
    renderShell(
      phStripHtml(-1) +
      '<div class="fh-card">' +
        '<h3>' + esc(COPY.PH_SCORES_TITLE) + '</h3>' +
        '<p class="fh-sub">' + esc(COPY.PH_SCORES_SUB) + '</p>' +
        scoreInputHtml('easy', 'fh-aps-', null) +
        scoreInputHtml('enjoy', 'fh-aps-', null) +
        (hideConf ? '' : scoreInputHtml('conf', 'fh-aps-', null)) +
        '<button class="fh-btn" id="fh-aps-save">' + esc(COPY.PH_SCORES_BTN) + '</button>' +
        '<div class="fh-msg" id="fh-aps-msg"></div>' +
      '</div>');
    document.getElementById('fh-aps-save').addEventListener('click', function () {
      var keys = hideConf ? ['easy', 'enjoy'] : ['easy', 'enjoy', 'conf'];
      var dayScores = {};
      for (var i = 0; i < keys.length; i++) {
        var v = document.getElementById('fh-aps-' + keys[i]).value;
        if (!validScore(v)) return setMsg('fh-aps-msg', COPY.SCORE_ERROR, false);
        dayScores[keys[i]] = Number(v);
      }
      setMsg('fh-aps-msg', COPY.SAVING, true);
      callGateway({ action: 'save', projectId: state.activeProjectId, day: 1, fields: {}, dayScores: dayScores })
        .then(function (data) {
          if (!data.ok) return setMsg('fh-aps-msg', data.error, false);
          if (state.currentDay === 1) { state.day = data.day || state.day; }
          else { state.phDay = data.day || state.phDay; }
          if (data.completion) state.completion = data.completion;
          writeStateCache();
          route();
        })
        .catch(function (err) { setMsg('fh-aps-msg', String(err), false); });
    });
  }

  function renderDay1Done() {
    renderShell(
      phStripHtml(-1) +
      '<div class="fh-card fh-center">' +
        '<h3>' + esc(COPY.PH_CELEBRATE_TITLE) + '</h3>' +
        '<p class="fh-sub">' + esc(COPY.PH_CELEBRATE_TEXT) + '</p>' +
        '<div class="fh-linkline"><a href="#" id="fh-ph-review">' + esc(COPY.PH_REVIEW_LINK) + '</a></div>' +
        '<div class="fh-linkline"><a href="#" id="fh-withdrawal-link">' + esc(COPY.WITHDRAWAL_LINK) + '</a></div>' +
      '</div>');
    document.getElementById('fh-ph-review').addEventListener('click', function (e) {
      e.preventDefault();
      state.forcedPhase = null;
      renderPowerHourPicker();
    });
    document.getElementById('fh-withdrawal-link').addEventListener('click', function (e) {
      e.preventDefault();
      renderWithdrawal();
    });
  }

  // The optional Withdrawal Helper (bh_withdrawal). Reachable from the Day-1
  // celebrate card and the tool picker; "done" marks the optional d1_withdrawal
  // tick (a usage marker — nothing requires it) and routes back.
  function renderWithdrawal() {
    renderShell(
      phStripHtml(-1) +
      '<div class="fh-card">' +
        '<h3>' + esc(COPY.WITHDRAWAL_TITLE) + '</h3>' +
        '<p class="fh-sub">' + esc(COPY.WITHDRAWAL_SUB) + ' ' + esc(COPY.PH_RESUME_NOTE) + '</p>' +
        '<div id="fh-tool"></div>' +
        '<button class="fh-btn fh-secondary" id="fh-wd-done">' + esc(COPY.WITHDRAWAL_DONE) + '</button>' +
        '<div class="fh-msg" id="fh-wd-msg"></div>' +
      '</div>');
    mountTool('bh_withdrawal', { sessionKey: 'ph-bh_withdrawal' });
    document.getElementById('fh-wd-done').addEventListener('click', function () {
      callGateway({ action: 'save', projectId: state.activeProjectId, day: 1, fields: { d1_withdrawal: true } })
        .then(function (data) {
          if (data.ok) {
            if (state.currentDay === 1) { state.day = data.day || state.day; }
            else { state.phDay = data.day || state.phDay; }
            if (data.completion) state.completion = data.completion;
            writeStateCache();
          }
          route();
        })
        .catch(function () { route(); });
    });
  }
  function renderPowerHourPicker() {
    var html = phStripHtml(-1) + '<div class="fh-card"><h3>' + esc(COPY.PH_REVIEW_LINK) + '</h3>';
    for (var i = 0; i < TOOLS.powerHour.length; i++) {
      html += '<button class="fh-btn fh-secondary fh-toolpick" data-idx="' + i + '">' + esc(TOOLS.powerHour[i].name) + '</button>';
    }
    html += '<button class="fh-btn fh-secondary" id="fh-pick-wd">' + esc(COPY.WITHDRAWAL_TITLE) + '</button>';
    html += '</div>';
    renderShell(html);
    var picks = rootEl.querySelectorAll('.fh-toolpick');
    for (var p = 0; p < picks.length; p++) {
      picks[p].addEventListener('click', function () {
        renderPowerHour(Number(this.getAttribute('data-idx')));
      });
    }
    document.getElementById('fh-pick-wd').addEventListener('click', function () {
      renderWithdrawal();
    });
  }

  /* ============================================================
   * DAILY — jumpstart → coach → tool → daily log (+ progress)
   * ============================================================ */
  function renderDaily() {
    var day = state.day || { fields: [] };
    var jumpDone = !!fieldVal(day, 'jumpstart');
    var anchor = state.setup.jumpstart || '';
    var loggedSomething = !!(fieldVal(day, 'wins') || fieldVal(day, 'exp') || fieldVal(day, 'opps'));
    var scoresVals = (day.scores && day.scores.values) || {};
    var hideConf = !!(state.confidence && state.confidence.optedOut);

    renderShell(
      '<div class="fh-strip"><div class="fh-strip-title">' + esc(COPY.DAILY_STRIP_TITLE) + '</div></div>' +

      // STEP 1 — jumpstart
      '<div class="fh-card' + (jumpDone ? ' fh-card-done' : '') + '">' +
        '<h3>' + esc(COPY.STEP1_TITLE) + (jumpDone ? ' <span class="fh-done-tick">✓</span>' : '') + '</h3>' +
        (anchor ? '<p class="fh-sub">' + esc(COPY.STEP1_ANCHOR.replace('{ANCHOR}', anchor)) + '</p>' : '') +
        '<label class="fh-check"><input type="checkbox" id="fh-jump"' + (jumpDone ? ' checked' : '') + '/> ' + esc(COPY.STEP1_CHECK) + '</label>' +
        '<div class="fh-msg" id="fh-jump-msg"></div>' +
      '</div>' +

      // STEP 2 — coach + tool
      '<div class="fh-card">' +
        '<h3>' + esc(COPY.STEP2_TITLE) + '</h3>' +
        '<p class="fh-sub">' + esc(COPY.STEP2_SUB) + '</p>' +
        '<div id="freedom-coach"></div>' +
        '<div class="fh-divider"></div>' +
        '<div id="fh-tool-area">' +
          '<p class="fh-sub" id="fh-tool-hint">' + esc(COPY.STEP2_TOOL_WAITING) + '</p>' +
          '<button class="fh-btn fh-secondary" id="fh-tool-direct">' + esc(COPY.STEP2_TOOL_DIRECT) + '</button>' +
          '<div id="fh-tool"></div>' +
        '</div>' +
      '</div>' +

      // STEP 3 — daily log
      '<div class="fh-card' + (loggedSomething ? ' fh-card-done' : '') + '">' +
        '<h3>' + esc(COPY.STEP3_TITLE) + (loggedSomething ? ' <span class="fh-done-tick">✓</span>' : '') + '</h3>' +
        '<div class="fh-field"><label class="fh-label">' + esc(COPY.STEP3_MINUTES) + '</label>' +
        '<input type="number" min="0" step="1" id="fh-min" value="' + esc(fieldVal(day, 'rbf') == null ? '' : fieldVal(day, 'rbf')) + '" /></div>' +
        dailyTextarea(day, 'exp') +
        dailyTextarea(day, 'wins') +
        dailyTextarea(day, 'opps') +
        dailyTextarea(day, 'notes') +
        scoreInputHtml('easy', 'fh-ds-', scoresVals.easy) +
        scoreInputHtml('enjoy', 'fh-ds-', scoresVals.enjoy) +
        (hideConf ? '' : scoreInputHtml('conf', 'fh-ds-', scoresVals.conf)) +
        (hideConf ? '' : '<label class="fh-check fh-conf"><input type="checkbox" id="fh-conf-forever"/> ' + esc(COPY.CONF_FOREVER) + '</label>') +
        '<button class="fh-btn" id="fh-day-save">' + esc(COPY.STEP3_SAVE) + '</button>' +
        '<div class="fh-msg" id="fh-day-msg"></div>' +
      '</div>' +

      // Progress (pull, never push)
      '<div class="fh-card fh-center">' +
        '<button class="fh-btn fh-secondary" id="fh-progress-btn">' + esc(COPY.PROGRESS_BTN) + '</button>' +
        '<div id="fh-progress"></div>' +
      '</div>');

    rootEl.addEventListener('input', function () { state.dirty = true; });

    // Step 1 — save the jumpstart tick immediately on change.
    document.getElementById('fh-jump').addEventListener('change', function () {
      var on = this.checked;
      setMsg('fh-jump-msg', COPY.SAVING, true);
      callGateway({ action: 'save', projectId: state.activeProjectId, day: state.currentDay, fields: { jumpstart: on } })
        .then(function (data) {
          if (!data.ok) return setMsg('fh-jump-msg', data.error, false);
          if (data.day) state.day = data.day;
          if (data.completion) state.completion = data.completion;
          writeStateCache();
          setMsg('fh-jump-msg', 'Saved ✓', true);
        })
        .catch(function (err) { setMsg('fh-jump-msg', String(err), false); });
    });

    // Step 2 — the coach (script injected on first daily render) + tool.
    loadCoachScript();
    document.getElementById('fh-tool-direct').addEventListener('click', function () {
      mountDailyTool(TOOLS.dailyDefault, '');
    });

    // Step 3 — one save for the whole log.
    document.getElementById('fh-day-save').addEventListener('click', function () {
      var fields = {
        rbf: document.getElementById('fh-min').value,
        exp: document.getElementById('fh-ta-exp').value,
        wins: document.getElementById('fh-ta-wins').value,
        opps: document.getElementById('fh-ta-opps').value,
        notes: document.getElementById('fh-ta-notes').value
      };
      var keys = hideConf ? ['easy', 'enjoy'] : ['easy', 'enjoy', 'conf'];
      var dayScores = {};
      var anyScore = false;
      for (var i = 0; i < keys.length; i++) {
        var v = document.getElementById('fh-ds-' + keys[i]).value;
        if (v !== '') {
          if (!validScore(v)) return setMsg('fh-day-msg', COPY.SCORE_ERROR, false);
          dayScores[keys[i]] = Number(v);
          anyScore = true;
        }
      }
      var payload = { action: 'save', projectId: state.activeProjectId, day: state.currentDay, fields: fields };
      if (anyScore) payload.dayScores = dayScores;
      var confForever = document.getElementById('fh-conf-forever');
      if (confForever && confForever.checked) payload.confidentForever = true;
      setMsg('fh-day-msg', COPY.SAVING, true);
      callGateway(payload)
        .then(function (data) {
          if (!data.ok) return setMsg('fh-day-msg', data.error, false);
          if (data.day) state.day = data.day;
          if (data.completion) state.completion = data.completion;
          state.dirty = false;
          writeStateCache();
          setMsg('fh-day-msg', COPY.STEP3_SAVED, true);
        })
        .catch(function (err) { setMsg('fh-day-msg', String(err), false); });
    });

    // Progress on demand.
    document.getElementById('fh-progress-btn').addEventListener('click', function () {
      var btn = this;
      btn.disabled = true;
      callGateway({ action: 'progressReview', projectId: state.activeProjectId })
        .then(function (data) {
          btn.disabled = false;
          var box = document.getElementById('fh-progress');
          if (!data.ok) { box.innerHTML = '<div class="fh-msg fh-bad">' + esc(data.error || 'Could not load progress.') + '</div>'; return; }
          box.innerHTML = progressHtml(data);
        })
        .catch(function () { btn.disabled = false; });
    });
  }

  function dailyTextarea(day, key) {
    var label = '';
    if (day && day.fields) {
      for (var i = 0; i < day.fields.length; i++) {
        if (day.fields[i].key === key) { label = day.fields[i].label; break; }
      }
    }
    if (!label) {
      var fallback = { exp: 'Real-World Freedom Experiments', wins: 'Wins', opps: 'Opportunities or Concerns', notes: 'Notes (optional)' };
      label = fallback[key] || key;
    }
    var val = fieldVal(day, key);
    return '<div class="fh-field"><label class="fh-label">' + esc(label) + '</label>' +
      '<textarea id="fh-ta-' + key + '" rows="2">' + esc(val == null ? '' : val) + '</textarea></div>';
  }

  function progressHtml(data) {
    if (!data.hasData) return '<p class="fh-sub">' + esc(COPY.PROGRESS_EMPTY) + '</p>';
    var mks = ['easy', 'enjoy', 'conf'];
    var names = { easy: 'Easy', enjoy: 'Enjoyable', conf: 'Confidence' };
    var html = '<h3>' + esc(COPY.PROGRESS_TITLE) + '</h3><table class="fh-table"><tr><th></th>' +
      '<th>' + esc(COPY.PROGRESS_BASELINE) + '</th><th>' + esc(data.currentLabel || 'Now') + '</th><th>Δ</th></tr>';
    for (var i = 0; i < mks.length; i++) {
      var k = mks[i];
      var b = data.baseline ? data.baseline[k] : null;
      var c = data.current ? data.current[k] : null;
      var d = data.fromBaseline ? data.fromBaseline[k] : null;
      html += '<tr><td>' + names[k] + '</td><td>' + esc(b == null ? '—' : b) + '</td><td>' +
        esc(c == null ? '—' : c) + '</td><td>' + esc(d == null ? '—' : (d > 0 ? '+' + d : d)) + '</td></tr>';
    }
    html += '</table>';
    if (data.last7 && data.last7.deltas) {
      html += '<p class="fh-sub">Last ~7 days (' + esc(data.last7.fromLabel || '') + '): ';
      var parts = [];
      for (var j = 0; j < mks.length; j++) {
        var dv = data.last7.deltas[mks[j]];
        if (dv != null) parts.push(names[mks[j]] + ' ' + (dv > 0 ? '+' + dv : dv));
      }
      html += esc(parts.join(' · ')) + '</p>';
    }
    return html;
  }

  /* ============================================================
   * TOOL MOUNTING (ai-tools-widget) + coach handoff
   * ============================================================ */
  function toolsConfigured() { return !!(state.engine && state.engineKey && window.AgtWidget); }

  function mountTool(botId, opts) {
    opts = opts || {};
    var holder = document.getElementById('fh-tool');
    if (!holder) return;
    if (!toolsConfigured()) {
      holder.innerHTML = '<div class="fh-msg fh-bad">' + esc(COPY.NOT_CONFIGURED) + '</div>';
      return;
    }
    unmountTool();
    var stub = document.createElement('div');
    stub.id = 'fh-tool-stub';
    stub.setAttribute('data-bot-id', botId);
    stub.setAttribute('data-engine', state.engine);
    stub.setAttribute('data-key', state.engineKey);
    if (state.draft) stub.setAttribute('data-draft', '1');
    stub.setAttribute('data-session-key', opts.sessionKey || (botId + '-default'));
    if (opts.firstMessageFrom) stub.setAttribute('data-first-message-from', opts.firstMessageFrom);
    holder.appendChild(stub);
    window.AgtWidget.mount(stub);
    state.toolMountedBot = botId;
  }
  function unmountTool() {
    var stub = document.getElementById('fh-tool-stub');
    if (stub && window.AgtWidget) { window.AgtWidget.unmount(stub); }
    if (stub && stub.parentNode) { stub.parentNode.removeChild(stub); }
    state.toolMountedBot = '';
  }

  function mountDailyTool(botId, promptText) {
    var hint = document.getElementById('fh-tool-hint');
    var direct = document.getElementById('fh-tool-direct');
    if (promptText) {
      // Ride the widget's first-message injection: the prompt lives in a
      // hidden text/markdown node, exactly like a lesson fixture would.
      var node = document.getElementById('fh-first-msg');
      if (!node) {
        node = document.createElement('script');
        node.type = 'text/markdown';
        node.id = 'fh-first-msg';
        document.body.appendChild(node);
      }
      node.textContent = promptText;
      if (hint) hint.textContent = COPY.STEP2_TOOL_LOADED;
    }
    if (direct) direct.style.display = 'none';
    mountTool(botId, {
      sessionKey: 'd' + state.currentDay + '-' + botId,
      firstMessageFrom: promptText ? 'fh-first-msg' : ''
    });
  }

  // coach.v3 injected from the folder THIS script came from, only once,
  // and only when the daily rail actually renders the coach div.
  function loadCoachScript() {
    if (state.coachLoaded) return;
    state.coachLoaded = true;
    if (typeof window.__FH_MOCK_CALL === 'function' && window.__FH_MOCK_NO_COACH) return;
    var base = SCRIPT_SRC.split('?')[0];
    var dir = base.slice(0, base.lastIndexOf('/') + 1);
    if (!dir) return;
    var s = document.createElement('script');
    s.src = dir + 'coach.v3.js';
    document.body.appendChild(s);
  }

  // The handoff: coach.v3's "Load into the tool below ↓" button.
  document.addEventListener('fc:prompt-send', function (ev) {
    var d = (ev && ev.detail) || {};
    mountDailyTool(TOOLS.routeBot(d.tool), String(d.prompt || ''));
    var stub = document.getElementById('fh-tool-stub');
    if (stub && stub.scrollIntoView) { try { stub.scrollIntoView({ behavior: 'smooth', block: 'start' }); } catch (e) {} }
  });

  // The coach just wrote the tracker (review card applied). Refresh the log
  // card SURGICALLY: refetch the day, fill only inputs the student has left
  // empty (never clobber typing), and confirm visibly. No re-render — the
  // live coach and tool widgets must not be torn down.
  document.addEventListener('fc:applied', function () {
    callGateway({ action: 'getDay', projectId: state.activeProjectId, day: state.currentDay })
      .then(function (data) {
        if (!data.ok || !data.day) return;
        state.day = data.day;
        writeStateCache();
        var map = { rbf: 'fh-min', exp: 'fh-ta-exp', wins: 'fh-ta-wins', opps: 'fh-ta-opps', notes: 'fh-ta-notes' };
        for (var k in map) {
          var el = document.getElementById(map[k]);
          if (!el) continue;
          var v = fieldVal(state.day, k);
          if (v != null && v !== '' && String(el.value || '').trim() === '') { el.value = v; }
        }
        setMsg('fh-day-msg', COPY.COACH_LOGGED, true);
      })
      .catch(function () {});
  });

  /* ============================================================
   * STYLES
   * ============================================================ */
  function injectStyles() {
    if (document.getElementById('fh-styles')) return;
    var css =
      '#freedom-home{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;color:#1d2733;line-height:1.5;}' +
      '#freedom-home .fh-wrap{max-width:720px;margin:0 auto;}' +
      '#freedom-home .fh-header{display:flex;align-items:center;justify-content:space-between;gap:10px;margin:6px 0 14px;}' +
      '#freedom-home .fh-daychip{display:inline-block;background:#2f6df6;color:#fff;font-weight:700;border-radius:999px;padding:4px 14px;font-size:14px;}' +
      '#freedom-home .fh-hi{font-size:15px;color:#4a5765;margin-top:6px;}' +
      '#freedom-home .fh-refresh{background:none;border:1px solid #c4cfd9;border-radius:8px;padding:7px 12px;color:#4a5765;cursor:pointer;font:inherit;font-size:13px;}' +
      '#freedom-home .fh-card{background:#fff;border:1px solid #e3e9ef;border-radius:14px;padding:18px;margin:0 0 14px;box-shadow:0 2px 8px rgba(20,40,70,.05);}' +
      '#freedom-home .fh-card-done{border-color:#bfe3c8;}' +
      '#freedom-home .fh-done-tick{color:#2c9a4b;font-weight:700;}' +
      '#freedom-home h3{margin:0 0 8px;font-size:17px;line-height:1.35;}' +
      '#freedom-home .fh-sub{color:#5a6875;font-size:14px;margin:4px 0 10px;}' +
      '#freedom-home .fh-label{display:block;font-size:13.5px;color:#42505e;margin:10px 0 4px;font-weight:600;}' +
      // Inputs/buttons are scoped to fh- classes and .fh-card children so the
      // widget's and coach's OWN controls (inside #fh-tool / #freedom-coach)
      // never inherit these.
      '#freedom-home .fh-field input,#freedom-home .fh-field textarea,#freedom-home .fh-card > input,#freedom-home .fh-card > textarea{width:100%;box-sizing:border-box;border:1px solid #c4cfd9;border-radius:8px;padding:10px;font-size:16px;font-family:inherit;color:#1d2733;background:#fff;text-align:left;}' +
      '#freedom-home .fh-btn{display:inline-block;margin-top:12px;background:#2f6df6;color:#fff;border:none;border-radius:10px;padding:12px 18px;font:inherit;font-weight:600;cursor:pointer;width:100%;}' +
      '#freedom-home .fh-btn:disabled{opacity:.55;cursor:default;}' +
      '#freedom-home .fh-btn.fh-secondary{background:#eef3f9;color:#2f4a68;}' +
      '#freedom-home .fh-check{display:flex;gap:9px;align-items:flex-start;font-size:14.5px;margin:10px 0;}' +
      '#freedom-home .fh-check input{width:auto;margin-top:3px;}' +
      '#freedom-home .fh-refresh{width:auto;margin-top:0;}' +
      '#freedom-home .fh-hdr-right{display:flex;gap:8px;align-items:center;flex:none;}' +
      '#freedom-home .fh-proj{border:1px solid #c4cfd9;border-radius:8px;padding:7px 8px;font:inherit;font-size:13px;color:#4a5765;background:#fff;max-width:170px;}' +
      '#freedom-home .fh-msg{margin-top:8px;font-size:13.5px;min-height:18px;}' +
      '#freedom-home .fh-good{color:#2c9a4b;}#freedom-home .fh-bad{color:#c0392b;}' +
      '#freedom-home .fh-note{background:#fff6e5;border:1px solid #f0dbae;border-radius:8px;padding:8px 10px;font-size:13.5px;margin:8px 0;}' +
      '#freedom-home .fh-divider{height:1px;background:#e3e9ef;margin:14px 0;}' +
      '#freedom-home .fh-center{text-align:center;}' +
      '#freedom-home .fh-linkline{margin-top:10px;font-size:14px;}' +
      '#freedom-home a{color:#2f6df6;}' +
      '#freedom-home .fh-footer{text-align:center;margin:6px 0 20px;font-size:14px;}' +
      '#freedom-home .fh-dots{display:flex;align-items:center;gap:6px;margin-bottom:10px;}' +
      '#freedom-home .fh-dot{width:9px;height:9px;border-radius:50%;background:#d7dfe8;}' +
      '#freedom-home .fh-dot-on{background:#2f6df6;}' +
      '#freedom-home .fh-dots-label{font-size:12.5px;color:#7a8794;margin-left:4px;}' +
      '#freedom-home .fh-strip{display:flex;align-items:center;justify-content:space-between;margin:0 0 10px;gap:10px;}' +
      '#freedom-home .fh-strip-title{font-weight:700;font-size:15px;}' +
      '#freedom-home .fh-strip-steps{display:flex;gap:6px;}' +
      '#freedom-home .fh-pip{width:26px;height:26px;border-radius:50%;background:#e3e9ef;color:#5a6875;display:flex;align-items:center;justify-content:center;font-size:13px;font-weight:700;}' +
      '#freedom-home .fh-pip-done{background:#2c9a4b;color:#fff;}' +
      '#freedom-home .fh-pip-now{background:#2f6df6;color:#fff;}' +
      '#freedom-home .fh-field{margin:8px 0;}' +
      '#freedom-home .fh-goal{background:#f4f8fd;border-radius:8px;padding:10px;font-size:14.5px;}' +
      '#freedom-home .fh-table{width:100%;border-collapse:collapse;font-size:14px;margin-top:8px;}' +
      '#freedom-home .fh-table th,#freedom-home .fh-table td{border-bottom:1px solid #e3e9ef;padding:6px 8px;text-align:center;}' +
      '#freedom-home .fh-table td:first-child,#freedom-home .fh-table th:first-child{text-align:left;}' +
      '#freedom-home .fh-toolpick{margin-top:8px;}' +
      '#fh-tool{margin-top:12px;}';
    var style = document.createElement('style');
    style.id = 'fh-styles';
    style.textContent = css;
    document.head.appendChild(style);
  }

  /* ============================================================
   * BOOT
   * ============================================================ */
  function boot() {
    rootEl = document.getElementById(CONFIG.CONTAINER_ID);
    if (!rootEl) return;
    injectStyles();
    state.engine = rootEl.getAttribute('data-engine') || '';
    state.engineKey = rootEl.getAttribute('data-key') || '';
    state.draft = rootEl.getAttribute('data-draft') === '1';
    state.fullTrackerUrl = rootEl.getAttribute('data-full-tracker-url') || '';

    // TEST HOOK — mock transport: skip identity entirely.
    if (typeof window.__FH_MOCK_CALL === 'function') {
      state.identity = (window.__FH_MOCK_IDENTITY || { accountId: 'mock', email: 'mock@test', firstName: 'Testy' });
      state.token = 'mock-token';
      rootEl.innerHTML = shellLoading();
      loadState(false);
      return;
    }

    handleResetParam();
    captureMagicLinkToken();
    stripTokenFromUrl();
    state.token = readLS(LS.token);

    // FAST PAINT (same pattern as loader.v7): token + cached identity +
    // cached snapshot -> paint instantly, verify + refresh in background.
    var cachedId = readIdentityCache();
    var cachedSnap = state.token ? readStateCache() : null;
    if (state.token && cachedId && cachedSnap) {
      state.identity = cachedId;
      hydrateFromCache(cachedSnap.snapshot);
      if (cachedSnap.snapshot.firstName && !state.identity.firstName) {
        state.identity.firstName = cachedSnap.snapshot.firstName;
      }
      route();
      verifyIdentityThenRefresh_(cachedId);
      return;
    }

    getIdentity().then(function (identity) {
      state.identity = identity;
      if (!state.token) { return attemptRecover(''); }
      var cached = readStateCache();
      if (cached) {
        hydrateFromCache(cached.snapshot);
        route();
        loadState(true);
      } else {
        rootEl.innerHTML = shellLoading();
        loadState(false);
      }
    });
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', boot);
  } else {
    boot();
  }
})();
